//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatLightToNUnitReportGenerator.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatLightToNUnitReportGenerator.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StatLightTestResults total=&quot;6&quot; ignored=&quot;1&quot; failed=&quot;2&quot; dateRun=&quot;2011-04-09 21:06:03&quot;&gt;
        ///  &lt;tests xapFileName=&quot;bin\Debug\SomeApplication.Tests.xap&quot;&gt;
        ///    &lt;test name=&quot;SomeApplication.Tests.ATest.My_first_test.&quot; resulttype=&quot;Passed&quot; timeToComplete=&quot;00:00:00&quot; /&gt;
        ///    &lt;test name=&quot;SomeApplication.Tests.Util.My_second_test.Another_test.&quot; resulttype=&quot;Passed&quot; timeToComplete=&quot;00:00:00&quot; /&gt;
        ///    &lt;test name=&quot;SomeApplication.Tests.Util.My_second_test.Assert_failure.&quot; resulttype=&quot;Failed&quot; timeToComplete=&quot;00:00:00.0090005&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatLightExample {
            get {
                return ResourceManager.GetString("StatLightExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StatLightTestResults total=&quot;1&quot; ignored=&quot;0&quot; failed=&quot;0&quot; dateRun=&quot;2011-04-09 21:06:03&quot;&gt;
        ///  &lt;tests xapFileName=&quot;bin\Debug\SomeApplication.Tests.xap&quot;&gt;
        ///    &lt;test name=&quot;SomeApplication.Tests.ATest.My_first_test.&quot; resulttype=&quot;Passed&quot; timeToComplete=&quot;00:00:00&quot; /&gt;
        ///  &lt;/tests&gt;
        ///&lt;/StatLightTestResults&gt;.
        /// </summary>
        internal static string StatLightSimpleExample {
            get {
                return ResourceManager.GetString("StatLightSimpleExample", resourceCulture);
            }
        }
    }
}
